# This is a basic workflow to help you get started with Actions 
name: Portfolio Website

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main    
      
env:

  #Common
  image_name : "pridhvi15/pridhviportfolio"
  version_long : ${{ github.sha }}
  version_short : ${{ env.version_long:0:7 }}
  server_ip : "54.196.16.219" # Change to reflect your Region
  docker_token : ${{ secrets.DOCKER_PAT_TOKEN }}
  pem_file : ${{ secrets.SECRET_PEM }}




jobs:
  devBuild:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: "pridhvi15"
          password: ${{ env.docker_token }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ env.image_name }}:${{ env.version_short }}
        

  mainBuild:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: "pridhvi15"
          password: ${{ env.docker_token }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.image_name }}:${{ env.version_short }}
   